Fix various unit test failures related to powermock running in JDK 11
Errors like:
[ERROR] initializationError(com.pinterest.secor.io.FileReaderWriterFactoryTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalAccessError: class jdk.internal.reflect.ConstructorAccessorImpl loaded by org.powermock.core.classloader.MockClassLoader @5c448ef cannot access jdk/internal/reflect superclass jdk.internal.reflect.MagicAccessorImpl

The errors only occur in JDK 9 and above, powermock (and its dependent jboss.javassist) has issues on JDK 9 and above, see https://stackoverflow.com/questions/50456726/mockclassloader-cannot-access-jdk-internal-reflect-superclass-jdk-internal-refle

Upgraded the powermock to latest version and used techniques like @PowerMockIgnore to defer un-related class's classloading to the system default classloader (instead of the powermock's classloader).

The other issue is mock's anyString() seems not matching argument Null, changed some unit tests to pass in a non-null argument.