Refactor GsUploadmanager for latest SDK usage towards GCS
* Supports throttlign GCS API calls with GS Rate limit and number of
threads.
* Support both putting whole content and streaming content.

If you get exceptions towards uploading with:

com.google.cloud.storage.StorageException: Error writing request body to
server

This is most likley due to you getting throttled / their API respons
429/5xx.

See https://cloud.google.com/storage/docs/request-rate as well.